spring:
  application:
    admin:
      enabled: false
  jmx:
    enabled: false
  # Database connection settings
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url:  ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  #JPA Settings
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      # ddl-auto: create-drop
    # show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_SMTP}
    password: ${PASSWORD_SMTP}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8081

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
